# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: us.icr.io/modernpets
  pullPolicy: Always

ingress:
  enabled: true
  hosts:
    - mmssearch.modernpets.us-south.containers.mybluemix.net
