# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: <REGISTRY>/<NAMESPACE> # Ex: us.icr.io/mynamespace
  pullPolicy: Always

ingress:
  enabled: true
  hosts:
    - mmssearch.<Ingress Subdomain> # Ex: mmssearch.myclustername.us-south.containers.mybluemix.net
