# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:  mycluster.icp:8500/jpetstore
  pullPolicy: Always

ingress:
  enabled: true
  hosts:
    - mycluster.icp
